### ISSUE TITLE
Does not appear to work for .pssproj

### ISSUE THREAD

**Issue by Droppers** [jRichardeau/vscode-vsproj#1]
Hello,

It sounds like a neat extension, but your extension does not appear to work with the latest VS Code. There is no output option for VSPROJ and including / excluding does not do anything.

It says: `command 'extension.vsproj.add' not found`

Workspace Configuration:
```
"settings": {
	"vsproj.itemType": {
		"*": "Content",
		".ps1": "Compile",
		".psd1": "Compile",
		".psm1": "Compile"
	},
	"vsproj.enabled": true,
	"vsproj.projExtension": "pssproj"
}
```

VS Code version: `1.39.2`

**Comment by jRichardeau** [comment]
Hello,

I'm using it on VS Code 1.40.x and there is no problem.

Can you tell me what is the output of the extension ?

![image](https://user-images.githubusercontent.com/4921182/68952058-36d60400-078d-11ea-99c8-75a17d00b95d.png)

**Comment by Droppers** [comment]
It turned out a group policy was breaking some vscode extensions, your extension works great :)!
