### ISSUE TITLE
How to exclude some file extensions?

### ISSUE THREAD

**Issue by Denny966** [jRichardeau/vscode-vsproj#2]
Everything works fine but I can't manage to exclude some files

```json
 "vsproj": {
    //Must be true to be activated on the current workspace
    "activate": true,
    //List of RegEx to exclude some files
    "exclude": [".orig","orig","*.orig"],
    "encoding": "utf-8"
 }
```

When I add an orig file to the project (which is in a workspace), it still adds the orig file to the njsproj

**Comment by jRichardeau** [comment]
Hey,
This property must contain regular expression, not glob pattern.
Try this instead : 
`\.orig$`

**Comment by Denny966** [comment]
Thanks for the reply, I've tried 
`"exclude": ["\.orig$"],`
and
`"exclude": [\.orig$],`

but both still adds them to njsproj

![image](https://user-images.githubusercontent.com/12098006/71782517-1717cb00-2fdb-11ea-8298-2c9be137dbfb.png)

**Comment by jRichardeau** [comment]
I think you have to escape `\`
Try this : 
`"exclude": ["\\.orig$"]`

**Comment by jRichardeau** [comment]
No response so I close the issue.
Let me know if it needs to be reopened
