### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by sirber** [jRichardeau/vscode-vsproj#3]
the extension is enabled and I see the name in the bottom status bar.

VSCode changes:
![image](https://user-images.githubusercontent.com/3911428/113860914-96fb8a80-9774-11eb-9082-85b41f6bd2dc.png)

VS project
![image](https://user-images.githubusercontent.com/3911428/113860961-a8449700-9774-11eb-92d3-1ea88c0b871b.png)

I renamed and deleted files form VS code left file tree

**Comment by jRichardeau** [comment]
Hello sirber,

Is there something outputted from extension in the output tab of the terminal ?

**Comment by sirber** [comment]
if I delete a file
![image](https://user-images.githubusercontent.com/3911428/113882975-c23da400-978b-11eb-8117-c19a766075e2.png)

it's in the project file (csproj)

**Comment by jRichardeau** [comment]
You have to configure the `vsproj.projExtension` option to `csproj`, it's `njsproj` by default.

**Comment by jRichardeau** [comment]
Don't forget to configure the right type for each file extension with the `vsproj.itemType` option

**Comment by sirber** [comment]
the project file is not updated? 

![image](https://user-images.githubusercontent.com/3911428/114042273-49a21a80-9853-11eb-9ab9-211038ca7b9c.png)

**Comment by sirber** [comment]
itemTypes, alright!

![image](https://user-images.githubusercontent.com/3911428/114042494-7bb37c80-9853-11eb-813e-6462b3cf0944.png)

**Comment by jRichardeau** [comment]
This is not the right format for `itemType`  configuration, this is a map of "extension"->"tag name" in proj file.

The default configuration is :
`{ "*": "Content", ".js": "Compile", ".ts": "TypeScriptCompile" }`

Meaning that `.js` files will be added with `<Compile>` tag, `.ts` file with `TypeScriptCompile` and all other files with `<Content>`

**Comment by sirber** [comment]
by default it did nothing

**Comment by sirber** [comment]
deleted a file does nothing, except adding a new line in the csproj

![image](https://user-images.githubusercontent.com/3911428/114047611-cf27c980-9857-11eb-83ab-09725555e3be.png)

config:
```
{
	"folders": [
		{
			"path": "C:\\Users\\sirbe\\Projects\\scms\\scms\\webapps\\Scms18"
		}
	],
	"settings": {
	   "vsproj": {
		  //Must be true to be activated on the current workspace
		  "activate": true,
		  //List of RegEx to exclude some files
		  "exclude": []
	},
	"vsproj.projExtension": "csproj",
	"vsproj.encoding": "utf-8",
	"vsproj.itemType": {
		"*": "Content",
		".js": "Content",
		".ts": "TypeScriptCompile"
	},
	}	
}
```

**Comment by sirber** [comment]
ok the file wasn't in the project, it seems.

**Comment by jRichardeau** [comment]
ok so it's working ? To be sure is adding a file working ?

**Comment by sirber** [comment]
it's breaking the file encoding, I cannot use this project, even if add file works :(

**Comment by jRichardeau** [comment]
Which encoding does it break?

**Comment by sirber** [comment]
https://github.com/jRichardeau/vscode-vsproj/issues/4#issuecomment-815888375

**Comment by sirber** [comment]
add file works

![image](https://user-images.githubusercontent.com/3911428/114386357-1e734000-9b5f-11eb-88b7-371293292920.png)
